# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'upwork' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upwork

  

  platform :ios, '9.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'upworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'upwork-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for upwork-tvOS

  target 'upwork-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
